url: "http://www.westhousehotelnewyork.com"

# Build settings
default_lang: 'en'
languages: ['en']

exclude: ['sitemap.json']
keep_files: ['assets']
rsync_copy: ['_assets']

page_gen:
  - data: 'Blog'
    template: 'blog-single'
    dir: 'blog'
  - data: 'Event'
    template: 'event-single'
    dir: 'event-in-nyc'
  - data: 'Amenities'
    template: 'amenities-single'
    dir: 'westhouse-hotel-amenities-nyc'
  - data: 'Offers'
    template: 'sample-offer-details'
    dir: 'sample-offer-details'
  - data: 'Dining'
    template: 'dining-single'
    dir: 'westhouse-hotel-new-york-dining'
  - data: 'Partners'
    template: 'partners-detail'
    dir: 'westhouse-hotel-new-york-partners'
  - data: 'BlogCategory'
    template: 'category-single'
    dir: 'category-single'
  - data: 'Partners'
    template: 'partners-detail'
    dir: 'glamsquad'
  - data: 'Offers'
    template: 'offers-single'
    dir: 'offers'
  - data: 'VRTour'
    template: 'vr-tour-single'
    dir: 'virtual-tour'
  - data: 'Neighborhood-Locations'
    template: 'neighborhood-single'
    dir: 'neighborhood-single'
  - data: 'Culinary-Guide'
    template: 'neighborhood-culinary-single'
    dir: 'culinary-single'
  - data: 'PPC-Landing-Page'
    template: 'ppc-landing-single'
    dir: ''
